pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    productThumbnail:
                        items: {  }
                        medias: {  }
                        name: productThumbnail
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1701940439
                        creationDate: 1701940439
                        preserveAnimation: false
