pimcore_elasticsearch_client:
    es_clients:
        default:
            hosts: ['elastic:9200']
            username: 'elastic'
            password: 'somethingsecret'
            logger_channel: 'pimcore.elasticsearch'
        statistics:
            hosts: ['statistics-node:9200']
            logger_channel: 'pimcore.statistics'

            #optional options
            ca_bundle: 'path/to/ca/cert'
            ssl_key: 'path/to/ssl/key'
            ssl_cert: 'path/to/ssl/cert'
            ssl_password: 'secretePW'
            ssl_verification: false #true is the default value
            http_options:
                proxy: 'http://localhost:8125'
            cloud_id: '123456789'
            api_key: 'secret-apikey'
        cloud:
            cloud_id: '123456789'
            api_key: 'secret-apikey'