_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation

search:
    path: /search
    controller: App\Controller\SearchController::searchAction
    methods: ['GET']

login:
    path: /login
    controller: App\Controller\LoginController::login

register:
    path: /register
    controller: App\Controller\RegisterController::register

cartadd:
    path: '/academy/cartadd/{id}'
    controller: 'App\Controller\DefaultController::addToCartAction'
    requirements:
        id: '\d+'